- name: Update packages ubuntu
  when: inventory_hostname in lookup('inventory_hostnames', 'ubuntu:prox')
  apt:
    name: "*"
    state: latest

- name: Update packages fedora
  when: inventory_hostname in groups['fedora']
  dnf:
    name: "*"
    state: latest

- name: Install essential packages ubuntu
  when: inventory_hostname in lookup('inventory_hostnames', 'ubuntu:prox')
  package:
    name:
      - vim
      - htop
      - tmux
      - speedtest-cli
      - qemu-guest-agent
    state: latest

- name: Install essential packages fedora
  when: inventory_hostname in groups['fedora']
  package:
    name:
      - vim
      - htop
      - tmux
      - speedtest-cli
      - dnf-utils
      - qemu-guest-agent
    state: latest

- name: Disable SSH password auth
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^#PasswordAuthentication yes"
    line: "PasswordAuthentication no"
  register: sshd_config

- name: Enable passwordless sudo for user1
  lineinfile:
    dest: /etc/sudoers
    regexp: "^%wheel"
    line: "user1 ALL=(ALL) NOPASSWD: ALL"
    validate: 'bash -c "cat /etc/sudoers %s | visudo -cf-"'

- name: Start qemu-guest-agent
  ansible.builtin.systemd_service:
    state: started
    name: qemu-guest-agent

- name: Enable qemu-guest-agent
  ansible.builtin.systemd_service:
    name: qemu-guest-agent
    enabled: true

- name: Restart ssh daemon
  service:
    name: sshd
    state: restarted
  when: sshd_config.changed

- name: Stop service cockpit
  when: inventory_hostname in groups['fedora']
  ansible.builtin.systemd_service:
    name: cockpit
    state: stopped
    enabled: false

- name: Stop cockpit.socket
  when: inventory_hostname in groups['fedora']
  ansible.builtin.systemd_service:
    name: cockpit.socket
    state: stopped
    enabled: false