- name: Update packages ubuntu
  when: inventory_hostname in lookup('inventory_hostnames', 'ubuntu:prox')
  apt:
    name: "*"
    state: latest

- name: Update packages fedora
  when: inventory_hostname in groups['fedora']
  dnf:
    name: "*"
    state: latest

- name: install syslog-ng
  package:
    name:
      - syslog-ng

- name: enable service
  ansible.builtin.systemd_service:
    name: syslog-ng.service
    state: enabled

- name: copy config
  ansible.builtin.copy:
    src: /home/user1/syslog-ng.conf
    dest: /etc/syslog-ng/syslog-ng.conf
    backup: yes
  register: syslog-ng_conf_copy

- name: restart service
  ansible.builtin.systemd_service:
    name: syslog-ng.service
    state: reloaded


