- name: update fedora server
  dnf:
    name: "*"
    state: latest

- name: Reboot required
  command: "/usr/bin/needs-restarting -r"
  register: reboot_required
  ignore_errors: True
  changed_when: False
  failed_when: reboot_required.rc == 2

- name: reboot after update
  when: reboot_required.rc == 1
  reboot:
    post_reboot_delay: 60
  throttle: 1

