- name: update fedora server
  when: inventory_hostname in groups['fedora']
  dnf:
    name: "*"
    state: latest

- name: check if reboot is required
  when: inventory_hostname in groups['fedora']
  ansible.builtin.shell:
    cmd: "needs-restarting -r -s"
  register: needs_restarting

- name: reboot after update
  when: inventory_hostname in groups['fedora']
  ansible.builtin.reboot:
  when: needs_restarting.rc == 1

- name: update ubuntu server
  when: inventory_hostname in groups['ubuntu']
  apt:
    name: "*"
    state: latest
