- name: update fedora server
  when: 
    - inventory_hostname in groups['fedora']
  dnf:
    name: "*"
    state: latest

- name: Reboot required
  when: 
    - inventory_hostname in groups['fedora']
  command: "/usr/bin/needs-restarting -r"
  register: reboot_required
  ignore_errors: True
  changed_when: False
  failed_when: reboot_required.rc == 2

- name: reboot after update
  when: inventory_hostname in groups['fedora']
  reboot:
    post_reboot_delay: 60
  throttle: 1
  when: needs_restarting.rc == 1

- name: update ubuntu server
  when: inventory_hostname in groups['ubuntu']
  apt:
    name: "*"
    state: latest
