- name: Stop service cockpit
  ansible.builtin.systemd_service:
    name: cockpit
    state: stopped

- name: Stop cockpit.socket
  ansible.builtin.systemd_service:
    name: cockpit.socket
    state: stopped